Amending uploadform and etc.
OpenUp-LabTakizawa/dcrs pull request #244
Opened 2024-02-29 02:19 UTC by kazutan1230

### What does this PR do?

- app/download/page.tsx
- components/jsonView.tsx
- components/useFormData.tsx
Adding a download page mock, thanks to @tanePON 

- components/imageInput.tsx
- components/imagePreview.tsx
- components/uploadFormHook.tsx
I deleted the imagePreview.tsx and merged the function of imagePreview to uploadFormHook.tsx,
because it is easy to register images into FormData.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

Github workflow checks have been passed.
I cheked at localhost and browser .

2024-02-29 04:48 UTC, Marukome0743 requested changes

2024-02-29 04:48 UTC, Marukome0743 commented on components/uploadFormHook.tsx
> +  }>({ file: null, name: '', source: '' })
```suggestion
type ImageData = {
  file: File
  name: string
  source: string
}

   // 添付画像を状態管理
  const [images, setImages] = React.useState<ImageData>({ file: new File([], ""), name: '', source: '' })
```

2024-02-29 04:48 UTC, Marukome0743 commented on components/uploadFormHook.tsx
> +    })
```suggestion
  // キャンセルボタンの処理
  const handleClickCancelButton = () => {
    setImages({
      ...images,
      file: new File([], ""),
      name: '',
      source: '',
    })
```

2024-03-04 08:10 UTC, Marukome0743 requested changes

2024-03-04 08:10 UTC, Marukome0743 commented on components/uploadFormHook.tsx
> +          <div>
Remove unused `<div>`.

2024-03-04 08:44 UTC, kazutan1230 commented on app/download/page.tsx
> +      <div className="hoge">
I'll remove it.

2024-03-04 08:45 UTC, kazutan1230 commented on app/download/page.tsx
> +                </a>
I'll change from<a> to <button>.

2024-03-04 08:45 UTC, kazutan1230 commented on components/jsonView.tsx
> +    <div>
I'll remove <div>.

2024-03-04 08:47 UTC, kazutan1230 commented on components/uploadFormHook.tsx
> +          <div>
I'll remove `<div>`.

2024-03-04 08:54 UTC, Marukome0743 approved these changes

2024-03-04 09:14 UTC, HaradaTakayuki approved these changes
確認しました

2024-03-04 09:28 UTC, merged