Confirm
OpenUp-LabTakizawa/dcrs pull request #266
Opened 2024-03-08 00:52 UTC by HaradaTakayuki

入力情報の確認画面を更新致しました。
問題なければ、マージをお願い致します。

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2024-03-08 00:55 UTC, Marukome0743 requested changes
正しくリベースが出来ていません。
再度、更新したファイルを確認して下さい。

また、自分のレポジトリでまず、
テストが通っているかどうかの
確認も宜しくお願い致します。

また、可能な限りコミットを結合して
意味のあるコミットを残して下さい。

2024-03-08 01:03 UTC, kazutan1230 commented
> 正しくリベースが出来ていません。 再度、更新したファイルを確認して下さい。
> 
> また、自分のレポジトリでまず、 テストが通っているかどうかの 確認も宜しくお願い致します。

同意です。

あと、貴レジストリに、
[Autofix.ci App Not Installed #1](https://github.com/HaradaTakayuki/dcrs/issues/1)というIssue出てますが、
これは対応しとかなくていいんですかね?

2024-03-08 02:31 UTC, HaradaTakayuki commented
> 正しくリベースが出来ていません。 再度、更新したファイルを確認して下さい。
> 
> また、自分のレポジトリでまず、 テストが通っているかどうかの 確認も宜しくお願い致します。
> 
> また、可能な限りコミットを結合して 意味のあるコミットを残して下さい。

修正を対応しました

2024-03-08 02:34 UTC, kazutan1230 commented
これ、
何もuploadページから何も入力フォームに入れなくても、
confirmページに飛べるのですが、
この仕様で合ってますか?

<img width="463" alt="スクリーンショット 2024-03-08 113021" src="https://github.com/OpenUp-LabTakizawa/dcrs/assets/145092901/42d602db-7bd2-49b4-83f6-7611b0372971">

あと、ブラウザ上の確認で、以下error吐いてますが、これは直さなくて大丈夫ですか?

<img width="619" alt="スクリーンショット 2024-03-08 113229" src="https://github.com/OpenUp-LabTakizawa/dcrs/assets/145092901/623596fc-7953-486c-9431-0668f9bea746">

2024-03-08 05:06 UTC, Marukome0743 commented
> > 正しくリベースが出来ていません。 再度、更新したファイルを確認して下さい。
> > また、自分のレポジトリでまず、 テストが通っているかどうかの 確認も宜しくお願い致します。
> > また、可能な限りコミットを結合して 意味のあるコミットを残して下さい。
> 
> 修正を対応しました

意味のないコミットを削除して頂いても宜しいでしょうか？

2024-03-19 08:40 UTC, Marukome0743 commented
申し訳ないですが、#295 で確認画面を作成しました。
従って、この PR を閉じます。

2024-03-19 08:40 UTC, closed without merging